import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import axios from "axios";
import logo from "../assets/ChatGPT_Genearted.png";

export default function SharedDeck() {
  const { shareId } = useParams();
  const [deck, setDeck] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    axios.get(`https://pitchforge-backend-wqez.onrender.com/decks/shared/${shareId}`)
      .then(res => setDeck(res.data))
      .catch(() => setError("Deck not found or link expired."));
  }, [shareId]);

  if (error) return (
    <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Poppins',system-ui,sans-serif", background: "#f1f1ee" }}>
      <p style={{ color: "#e53e3e", fontSize: "16px" }}>{error}</p>
    </div>
  );

  if (!deck) return (
    <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Poppins',system-ui,sans-serif", background: "#f1f1ee" }}>
      <p style={{ color: "#7a9a50" }}>Loading pitch deck...</p>
    </div>
  );

  const result = deck.data;
  const G = "#26851d";
  const BG = "#f1f1ee";
  const SHADOW_OUT = "6px 6px 14px #c8d4b8, -6px -6px 14px #ffffff";
  const SHADOW_IN = "inset 4px 4px 10px #c8d4b8, inset -4px -4px 10px #ffffff";
  const SHADOW_BTN = "4px 4px 10px #c8d4b8, -4px -4px 10px #ffffff";

  return (
    <div style={{ minHeight: "100vh", background: BG, fontFamily: "'Poppins',system-ui,sans-serif" }}>
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />

      {/* Navbar */}
      <nav style={{ background: BG, boxShadow: "0 4px 12px #c8d4b8", padding: "0 20px", height: "56px", display: "flex", alignItems: "center", justifyContent: "space-between", position: "sticky", top: 0, zIndex: 50 }}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <img src={logo} alt="PitchForge" style={{ width: "36px", height: "36px", borderRadius: "9px", objectFit: "contain" }} />
          <span style={{ fontWeight: "700", fontSize: "15px", color: "#2d3a1a" }}>PitchForge</span>
        </div>
        <span style={{ fontSize: "12px", color: "#7a9a50", fontWeight: "500" }}>Shared Pitch Deck</span>
      </nav>

      <div style={{ maxWidth: "760px", margin: "0 auto", padding: "40px 16px 80px" }}>

        {/* Cover */}
        <div style={{ background: `linear-gradient(135deg, #2d3a1a 0%, #4a6329 100%)`, borderRadius: "20px", padding: "40px 24px", textAlign: "center", marginBottom: "16px" }}>
          <p style={{ fontSize: "11px", color: G, fontWeight: "600", letterSpacing: "0.15em", textTransform: "uppercase", margin: "0 0 14px" }}>{deck.deck_type} pitch deck</p>
          <h2 style={{ fontSize: "clamp(20px,4vw,30px)", fontWeight: "700", color: "#fff", margin: "0 0 10px", lineHeight: "1.3" }}>{result.title}</h2>
          {result.tagline && <p style={{ fontSize: "15px", color: "rgba(255,255,255,0.85)", margin: "0 0 10px", fontStyle: "italic" }}>"{result.tagline}"</p>}
          <p style={{ fontSize: "12px", color: "#7a9a50", margin: "0" }}>Generated by PitchForge AI</p>
        </div>

        {/* Cards grid */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))", gap: "14px", marginBottom: "14px" }}>
          {[["Problem", result.problem], ["Solution", result.solution], ["Target Audience", result.target_audience], ["Market Size", result.market_size]].map(([l, v]) => (
            <div key={l} style={{ background: BG, borderRadius: "16px", boxShadow: SHADOW_OUT, padding: "22px" }}>
              <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 8px" }}>{l}</p>
              <p style={{ fontSize: "13.5px", color: "#2d3a1a", lineHeight: "1.7", margin: "0" }}>{v}</p>
            </div>
          ))}
        </div>

        {/* Business Model */}
        <div style={{ background: BG, borderRadius: "16px", boxShadow: SHADOW_OUT, padding: "22px", marginBottom: "14px" }}>
          <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 8px" }}>Business Model</p>
          <p style={{ fontSize: "13.5px", color: "#2d3a1a", lineHeight: "1.7", margin: "0" }}>{result.business_model}</p>
        </div>

        {/* Competitors */}
        <div style={{ background: BG, borderRadius: "16px", boxShadow: SHADOW_OUT, padding: "22px", marginBottom: "14px" }}>
          <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 12px" }}>Competitors</p>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>
            {result.competitors.map((c, i) => (
              <span key={i} style={{ background: BG, color: "#2d3a1a", borderRadius: "20px", padding: "5px 14px", fontSize: "12px", fontWeight: "600", boxShadow: SHADOW_BTN }}>{c}</span>
            ))}
          </div>
        </div>

        {/* SWOT */}
        <div style={{ background: BG, borderRadius: "16px", boxShadow: SHADOW_OUT, padding: "22px", marginBottom: "14px" }}>
          <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 16px" }}>SWOT Analysis</p>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))", gap: "10px" }}>
            {[["Strengths", "#2d6a2d"], ["Weaknesses", "#8b1a1a"], ["Opportunities", "#1a3d8b"], ["Threats", "#7a5200"]].map(([l, tc]) => (
              <div key={l} style={{ background: BG, borderRadius: "12px", padding: "16px", boxShadow: SHADOW_IN }}>
                <p style={{ fontSize: "10px", fontWeight: "700", color: tc, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 10px" }}>{l}</p>
                {result.swot[l.toLowerCase()].map((item, i) => <p key={i} style={{ fontSize: "12px", color: "#2d3a1a", margin: "0 0 5px", lineHeight: "1.6" }}>· {item}</p>)}
              </div>
            ))}
          </div>
        </div>

        {/* Financials */}
        <div style={{ background: BG, borderRadius: "16px", boxShadow: SHADOW_OUT, padding: "22px", marginBottom: "14px" }}>
          <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 16px" }}>Financials</p>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(120px,1fr))", gap: "10px" }}>
            {[["Startup cost", result.financials.startup_cost], ["Monthly revenue", result.financials.monthly_revenue], ["Monthly expenses", result.financials.monthly_expenses], ["Profit / loss", result.financials.profit_loss], ["Break even", result.financials.break_even]].map(([l, v]) => (
              <div key={l} style={{ background: BG, borderRadius: "12px", padding: "14px", textAlign: "center", boxShadow: SHADOW_IN }}>
                <p style={{ fontSize: "10px", color: "#7a9a50", margin: "0 0 6px", fontWeight: "500" }}>{l}</p>
                <p style={{ fontSize: "13px", fontWeight: "700", color: "#2d3a1a", margin: "0" }}>{v}</p>
              </div>
            ))}
          </div>
        </div>

        {/* GTM */}
        <div style={{ background: BG, borderRadius: "16px", boxShadow: SHADOW_OUT, padding: "22px", marginBottom: "14px" }}>
          <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 8px" }}>Go-to-Market Strategy</p>
          <p style={{ fontSize: "13.5px", color: "#2d3a1a", lineHeight: "1.7", margin: "0" }}>{result.go_to_market}</p>
        </div>

        {/* Validation */}
        {result.validation && (
          <div style={{ background: BG, borderRadius: "16px", boxShadow: SHADOW_OUT, padding: "22px", marginBottom: "14px" }}>
            <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 16px" }}>Business Concept Validation</p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: "10px", marginBottom: "14px" }}>
              {[["Viability Score", result.validation.viability_score], ["Market Readiness", result.validation.market_readiness], ["Competition Level", result.validation.competition_level]].map(([l, v]) => (
                <div key={l} style={{ background: BG, borderRadius: "12px", padding: "14px", textAlign: "center", boxShadow: SHADOW_IN }}>
                  <p style={{ fontSize: "10px", color: "#7a9a50", margin: "0 0 6px", fontWeight: "500" }}>{l}</p>
                  <p style={{ fontSize: "13px", fontWeight: "700", color: "#2d3a1a", margin: "0" }}>{v}</p>
                </div>
              ))}
            </div>
            <div style={{ background: BG, borderRadius: "12px", padding: "14px", boxShadow: SHADOW_IN }}>
              <p style={{ fontSize: "10px", color: "#7a9a50", margin: "0 0 6px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.08em" }}>Overall Verdict</p>
              <p style={{ fontSize: "13px", color: "#2d3a1a", lineHeight: "1.7", margin: "0" }}>{result.validation.overall_verdict}</p>
            </div>
          </div>
        )}

        {/* Improvements */}
        {result.improvements?.length > 0 && (
          <div style={{ background: BG, borderRadius: "16px", boxShadow: SHADOW_OUT, padding: "22px", marginBottom: "14px" }}>
            <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 14px" }}>Improvement Suggestions</p>
            {result.improvements.map((imp, i) => (
              <div key={i} style={{ display: "flex", gap: "12px", alignItems: "flex-start", marginBottom: "10px" }}>
                <div style={{ width: "24px", height: "24px", borderRadius: "50%", background: G, color: "#fff", fontSize: "11px", fontWeight: "700", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{i + 1}</div>
                <p style={{ fontSize: "13px", color: "#2d3a1a", lineHeight: "1.6", margin: "0" }}>{imp}</p>
              </div>
            ))}
          </div>
        )}

        {/* Similar Startups */}
        {result.similar_startups?.length > 0 && (
          <div style={{ background: BG, borderRadius: "16px", boxShadow: SHADOW_OUT, padding: "22px", marginBottom: "14px" }}>
            <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.1em", textTransform: "uppercase", margin: "0 0 14px" }}>Similar Successful Startups</p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: "10px" }}>
              {result.similar_startups.map((s, i) => (
                <div key={i} style={{ background: BG, borderRadius: "12px", padding: "16px", boxShadow: SHADOW_IN }}>
                  <p style={{ fontSize: "13px", fontWeight: "700", color: "#2d3a1a", margin: "0 0 6px" }}>{s.name}</p>
                  <p style={{ fontSize: "11px", color: "#7a9a50", margin: "0 0 8px", lineHeight: "1.5" }}>{s.description}</p>
                  <p style={{ fontSize: "11px", color: "#2d3a1a", margin: "0", lineHeight: "1.5", background: "#e8f0e0", padding: "6px 10px", borderRadius: "8px" }}>💡 {s.relevance}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* CTA */}
        <div style={{ background: `linear-gradient(135deg, #2d3a1a 0%, #4a6329 100%)`, borderRadius: "16px", padding: "28px 24px", textAlign: "center", marginBottom: "24px" }}>
          <p style={{ fontSize: "11px", fontWeight: "600", color: G, letterSpacing: "0.12em", textTransform: "uppercase", margin: "0 0 10px" }}>Call to Action</p>
          <p style={{ fontSize: "14px", color: "#cde88a", lineHeight: "1.8", margin: "0" }}>{result.call_to_action}</p>
        </div>

        {/* Footer */}
        <div style={{ textAlign: "center" }}>
          <p style={{ fontSize: "12px", color: "#aaa" }}>
            Created with <a href="http://localhost:5173" style={{ color: G, fontWeight: "600", textDecoration: "none" }}>PitchForge AI</a>
          </p>
        </div>
      </div>

      <style>{`
        @media (max-width: 768px) {
          nav span:last-child { display: none; }
        }
      `}</style>
    </div>
  );
}